# This workflow deploy beta anytask locally

name: Deploy local beta

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Deploy
        run: source loy_local_beta/run.sh
