# This workflow deploy beta anytask locally

name: Deploy local beta

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Deploy
        run: |
          apt-get --install virtualenv
          chmod +x deploy_local_beta/run.sh
          source deploy_local_beta/run.sh --python-path=python2
