# This workflow deploy beta anytask locally

name: Deploy local beta

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Install virtualenv
        run: pip2 install virtualenv
      - name: Deploy
        run: source deploy_local_beta/run.sh --python-path=python2
