name: Run task

on:
  workflow_dispatch:
    inputs:
      task:
        description: 'Task title'
        required: true
      repo:
        description: 'Repository with command to be run'
        required: true
      run_cmd:
        description: 'Command in repository to be run'
        required: true
      files:
        description: 'Files urls to be tested'
        required: true
      docker_image:
        description: 'Docker image to run tests in it'
        required: true
      timeout:
        description: 'Timeout of running worker'
        required: true


jobs:
  run_task:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone anytask/easyci
        run: |
          # TODO: remove -b easyci after merge to master
          git clone --depth 1 --filter=blob:none --sparse -b easyci https://github.com/znick/anytask
          cd anytask
          git sparse-checkout init --cone
          git sparse-checkout set easyci
          cd easyci
          chmod +x run_worker.sh

      - name: Run easyci worker
        working-directory: ./anytask/easyci/
        run: >
            ./run_worker.sh 
            ${{ github.event.inputs.task }} 
            ${{ github.event.inputs.repo }}
            ${{ github.event.inputs.run_cmd }}
            '${{ github.event.inputs.files }}'
            ${{ github.event.inputs.docker_image }}
            ${{ github.event.inputs.timeout }}

